type fontlist = {
  font: string;
  name: string;
};

const fontList: fontlist[] = [
  { font: "Handletter", name: "손편지체" },
  { font: "SangSangShin", name: "상상신과장" },
  { font: "Middleschool_student", name: "중학생" },
  { font: "Mongdol", name: "몽돌" },
  { font: "Gomsin", name: "곰신체" },
  { font: "Bareun_hipi", name: "바른히피" },
  { font: "Somi", name: "소미체" },
  { font: "Gootneaeum", name: "꽃내음" },
  { font: "Hana_handwriting", name: "하나손글씨" },
  { font: "Galmetgol", name: "갈맷글" },
  { font: "Shy_college_student", name: "수줍은 대학생" },
  { font: "Gothic_Goding", name: "고딕 아니고 고딩" },
  { font: "SlowSlow", name: "느릿느릿체" },
  { font: "Bumsom", name: "범솜체" },
  { font: "Mugunghwa", name: "무궁화" },
  { font: "Daughter_handwriting", name: "우리딸 손글씨" },
  { font: "Daheng", name: "다행체" },
  { font: "Sungsil", name: "성실체" },
  { font: "Pretty_Left_handed", name: "왼손잡이도 예뻐" },
  { font: "Mago", name: "마고체" },
  { font: "Anssang", name: "안쌍체" },
  { font: "Amsterdam", name: "암스테르담" },
  { font: "Kanginhan", name: "강인한 위로" },
  { font: "Se-hwa", name: "세화체" },
  { font: "Grandpa_sharing", name: "할아버지의나눔" },
  { font: "Beeunhye", name: "배은혜체" },
  { font: "Shining_star", name: "반짝반짝 별" },
  { font: "Polar_Star", name: "북극성" },
  { font: "Dajin", name: "다진체" },
  { font: "Rose", name: "장미체" },
  { font: "Restart", name: "다시시작해" },
  { font: "Wild", name: "와일드" },
  { font: "My_wife_writing", name: "나의 아내 손글씨" },
  { font: "Mini_handwriting", name: "미니 손글씨" },
  { font: "Bujangnim_nunchi", name: "부장님 눈치체" },
  { font: "Bbang_gunimom", name: "빵구니맘 손글씨" },
  { font: "mom_to_daughter", name: "딸에게 엄마가" },
  { font: "Bisang", name: "비상체" },
  { font: "Yuni_ddingddang", name: "유니 띵땅띵땅" },
  { font: "Fairytale_ddobak", name: "동화또박" },
  { font: "Hyejun", name: "혜준체" },
  { font: "White_angel", name: "백의의 천사" },
  { font: "Se-a", name: "세아체" },
  { font: "Korea_hero", name: "대한민국 열사체" },
  { font: "Mingyung", name: "예쁜 민경체" },
  { font: "Treegarden", name: "나무정원" },
  { font: "Garam", name: "가람연꽃" },
  { font: "Hardworking", name: "열일체" },
  { font: "Ainmom", name: "아인맘 손글씨" },
  { font: "Yeonji", name: "연지체" },
  { font: "Saying_tobe_strong", name: "힘내라는 말보단" },
  { font: "Future_tree", name: "미래나무" },
  { font: "Love_son", name: "사랑해 아들" },
  { font: "Ddobakddobak", name: "또박또박" },
  { font: "Jayoo", name: "아줌마 자유" },
  { font: "Father_loveletter", name: "아빠의 연애편지" },
  { font: "Okbi", name: "옥비체" },
  { font: "Become_one", name: "하나되어 손글씨" },
  { font: "Doing_well", name: "잘하고 있어" },
  { font: "Sanghea_chanmi", name: "상해찬미체" },
  { font: "Geumeunbohwa", name: "금은보화" },
  { font: "Kimyooyee", name: "김유이체" },
  { font: "Baby_love", name: "아기사랑체" },
  { font: "Orbit_of_moon", name: "달의궤도" },
  { font: "Unggungqui", name: "엉겅퀴체" },
  { font: "Mujinjang", name: "무진장체" },
  { font: "Hanyoon", name: "한윤체" },
  { font: "Ggeuteumuri", name: "끄트머리" },
  { font: "Dot_font", name: "점꼴체" },
  { font: "Syning_19", name: "열아홉의 반짝임" },
  { font: "Yammy", name: "맛있는체" },
  { font: "Ddakdandan", name: "따악단단" },
  { font: "Yedang", name: "예당체" },
  { font: "Kangbujang", name: "강부장님체" },
  { font: "Kimjuim", name: "야근하는 김주임" },
  { font: "Koreageulggol", name: "고려글꼴" },
  { font: "Warm_farewell", name: "따뜻한 작별" },
  { font: "Newly_married", name: "신혼부부" },
  { font: "Kyuri_diary", name: "규리의 일기" },
  { font: "GibbemBalgeum", name: "기쁨밝음" },
  { font: "Grandma_wring", name: "외할머니글씨" },
  { font: "Hope_nuri", name: "희망누리" },
  { font: "Meaningful_hanguel", name: "의미있는 한글" },
  { font: "Fighting_hyonam", name: "효남 늘 화이팅" },
  { font: "White_kkorisuri", name: "흰꼬리수리" },
  { font: "Deagwang_mirror", name: "대광유리" },
  { font: "Firefighter_prayer", name: "소방관의 기도" },
  { font: "Summer_letter", name: "여름글씨" },
  { font: "Round_destiny", name: "둥근인연" },
  { font: "Jungeun", name: "정은체" },
  { font: "Happy_dobi", name: "행복한 도비" },
  { font: "Haram", name: "하람체" },
  { font: "Hardworking_donghee", name: "노력하는 동희" },
  { font: "I_survive", name: "나는 이겨낸다" },
  { font: "Bareun_mental", name: "바른정신" },
  { font: "Father_handwriting", name: "아빠글씨" },
  { font: "Chulpil_writing", name: "철필글씨" },
  { font: "Choding_hope", name: "초딩희망" },
  { font: "Love_mom", name: "엄마사랑" },
  { font: "Global_Hangul", name: "세계적인 한글" },
  { font: "Coco", name: "코코체" },
  { font: "Dache_love", name: "다채사랑" },
  { font: "Kalguksu", name: "칼국수" },
  { font: "Pride_jiu", name: "자부심지우" },
  { font: "Hyukee", name: "혁이체" },
  { font: "Beakeumrye", name: "야채장수 백금례" },
  { font: "Bud_tree", name: "버드나무" },
  { font: "Parkgyunga", name: "진주 박경아체" },
  { font: "Flower_tree", name: "아름드리 꽃나무" },
];
export { fontList };
